Q-4. Imagine you working as a sale manager now you need to predict the Revenue
and whether that particular revenue is on the weekend or not and find the
Informational_Duration using the Ensemble learning algorithm.

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingRegressor

In [2]:
df = pd.read_csv("C:\\Users\\MGC\\Downloads\\assignment\\online_shoppers_intention.csv\\online_shoppers_intention.csv")

In [27]:
df

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,1,1,1,1,2,0,0
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,2,2,2,1,2,2,0,0
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,2,4,1,9,3,2,0,0
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,2,3,2,2,4,2,0,0
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,2,3,3,1,4,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,1,4,6,1,1,2,1,0
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,7,3,2,1,8,2,1,0
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,7,3,2,1,13,2,1,0
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,7,2,2,3,11,2,0,0
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,7,3,2,1,2,0,1,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Month"] = le.fit_transform(df["Month"])
df["VisitorType"] = le.fit_transform(df["VisitorType"])
df["Weekend"] = le.fit_transform(df["Weekend"])
df["Revenue"] = le.fit_transform(df["Revenue"])

In [9]:
X = df.drop(['Revenue', 'Weekend'], axis=1)  # Features
y_revenue = df['Revenue']  # Target variable for revenue prediction
y_weekend = df['Weekend']  # Target variable for weekend prediction

# splitting the data into training and testing sets
X_train, X_test, y_revenue_train, y_revenue_test, y_weekend_train, y_weekend_test = train_test_split(
    X, y_revenue, y_weekend, test_size=0.2, random_state=42)

# Choosing the ensemble learning algorithm (Random Forest)
model_revenue = RandomForestClassifier()  # Random Forest for revenue prediction
model_weekend = RandomForestClassifier()  # Random Forest for weekend prediction

# Training the models
model_revenue.fit(X_train, y_revenue_train)
model_weekend.fit(X_train, y_weekend_train)

# Evaluating the models (optional)
revenue_accuracy = model_revenue.score(X_test, y_revenue_test)
weekend_accuracy = model_weekend.score(X_test, y_weekend_test)
print("Revenue Accuracy:", revenue_accuracy)
print("Weekend Accuracy:", weekend_accuracy)

Revenue Accuracy: 0.8909164639091647
Weekend Accuracy: 0.7619626926196269

In [23]:
X = df.drop(['Informational_Duration'], axis=1)  # Features
y = df['Informational_Duration']  # Target variable

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Choosing the ensemble learning algorithm (Random Forest)
model = GradientBoostingRegressor()  # Random Forest for regression

# Training the model
model.fit(X_train, y_train)

# Evaluating the model (optional)
accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.40523173797280665